name = "NRS3DeSitter"
defaultTargets = ["NRS3DeSitter"]

[leanOptions]
autoImplicit = false

[[require]]
name = "NavaRobertsonIndependent"
git = "https://github.com/naype888-cloud/nava-robertson-schrodinger.git"
rev = "3bb4d4ebd8536c059cdc21e26c001ad854a017c9"

[[lean_lib]]
name = "NRS3DeSitter"
